### ISSUE TITLE
 Geckoview at Api level 29 or upper, not working

### ISSUE THREAD

**Issue by ghost** [Daddoon/Xamarin.Android.GeckoView#25]
Hi @Daddoon 

Hope you are doing well.....

I am working with Geckoview in blazor for android on the API level 29 is not working. Only display white screen.
Error comes on the output list is **_"[GeckoConsole] [JavaScript Error: "TypeError: state is undefined" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 2717}]"_**

When I am using Geckoview in blazor for android on the API level 28 or below of the API level 28 its working fine.

![Error](https://user-images.githubusercontent.com/45271777/133981584-f5f31ec9-8859-42af-966f-8289a6806e9c.png)
![Working](https://user-images.githubusercontent.com/45271777/133981592-24d77f28-7d1a-4512-8143-8408205926a9.png)

please guide me.

**Comment by Daddoon** [comment]
As i said on the BlazorMobile github project i don't have time at the moment to fix this issue. Maybe in October, i don't know.
The issue on API 29 is related to a bug on GeckoView on new Android versions, on how architecture images are managed.

In order to fix this issue, the current GeckoView 69 AAR image should be updated to GeckoView 77 or better.
However, there is some Android bindings to rewrite, and so the analysis on my side can take some time.

An other fix in the meantime would be to load BlazorMobile on the regular Android browser in Xamarin if API 29 or better is detected, meaning loading a Chrome view instead of a GeckoView, but maybe some behaviors may miss.

**Comment by Daddoon** [comment]
You may consider to migrate to .NET MAUI in the future for your app: https://docs.microsoft.com/en-us/shows/XamarinShow/Introduction-to-NET-MAUI-Blazor--The-Xamarin-Show

https://github.com/dotnet/maui
