### ISSUE TITLE
is Xamarin.Android.GeckoView still maintained

### ISSUE THREAD

**Issue by ghisbo** [Daddoon/Xamarin.Android.GeckoView#26]
I see this is for Android up to V9. Is The geckoview trail dead end?
We want to embed geckoview in Xamarin to make a android browser but i see little or  no action on geckoview after 2019.

**Comment by Daddoon** [comment]
Hi,

This project was mainly made and used for my **BlazorMobile** project, that i have now archived as it is less relevant, because Microsoft released **.NET MAUI Blazor / Blazor Mobile bindings** that does the same thing.

GeckoView was used in order to have a same codebase and behavior in the browser for every supported Android version, as some older systems didn't even had the **WebAssembly support** in them, required for the BlazorMobile implementation at runtime. By using GeckoView instead of the Android native browser, i was sure that every OS have a WebAssembly support.

I didn't have worked much on that since everything was working fine on my BlazorMobile project, now deprecated/archived.

I tried sometime to update the GeckoView engine, but it is not so easy as the GeckoView API had some breaking change at some level.

The thing is, that in order to generate the correct C# Bindings for Xamarin, you have to expose some Java class path, as you can see in the source code, if they are not automatically discovered, and sometime creating some additional class/partial class in order to workaround some Java reflection generation issue.

This mean that if things doesn't work out of the box while trying to compile a new **.aar** archive of a GeckoView version, you will likely have to read the corresponding documentation version of Java in order to guess what kind of possible C# binding is missing in the API. You will likely find what because you will see where the C# bindings are not compiling, but sometime on some part, it seem that some digging is needed.

Actually, a more recent version of GeckoView is needed in order to support from Android 29 and greater (a bug has been fixed), so you may need to seek the latest stable version of GeckoView on Mozilla Maven repository. I'm talking about the **.aar** file and possibly **javadoc** files, that you will have to update in the Xamarin.Android.GeckoView bindings project.

Unfortunately, i don't have the time window for upgrading this at the moment, and there is not a lot of demand.
But feel free to try to upgrade and generate the correct bindings, as the source code is available.

I may help if you need some guidance.

**Comment by ghisbo** [comment]
Thanks for the speedy reply.  i find the evolution on geckoview not very promissing and i do not know if the effort to keep this updated is not too heavy for me. I  think it is out of my league.
Thanks for your feedback, it helped me in my decision.
